version: 2

sources:

  - name: greenery_db # name of the source 
    schema: public # this is the schema our raw data lives in
    database: dbt # this is the name of our database

    quoting:
      database: false
      schema: false
      identifier: false

    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 48, period: hour}

    tables:
      - name: users 
        loaded_at_field: created_at
        description: >
          Contains information about all Greenery users
      - name: addresses 
        description: >
          Contains information about all Greenery users' addresses
      - name: orders 
        loaded_at_field: created_at
        description: >
          Contains information about all Greenery orders
      - name: order_items
        description: >
          Contains information about the items on each order
      - name: events 
        loaded_at_field: created_at
        description: >
          Contains information about all tracking events on Greenery's website
      - name: products 
        description: >
          Contains information about all Greenery products
      - name: promos 
        description: >
          Contains information about all Greenery promotions