version: 2

models:
  - name: fct_user_funnel
    description: >-
      Puchase funnel fact by users
    columns:
      - name: stage
        description: The stage in purchase funnel
        tests:
          - unique
          - not_null
          - accepted_values:
               values: ['Visit', 'Sign Up', 'Added to Cart', 'Purchase']
      - name: amount_of_users
        description: Total amount of users which reached the funnel stage
        tests:
          - not_null
      - name: amount_of_users_at_prev_step
        description: Total amount of users which reached the previous funnel stage
      - name: drop_off
        description: The percentage of users that drop off between the stages
  - name: fct_web_session
    description: >-
      Web Session fact
    columns:
      - name: session_id
        description: Unique session ID
        tests:
          - unique
          - not_null
      - name: user_id
        description: Unique user ID
        tests:
          - not_null
      - name: page_views_in_session
        description: The amount of page views in the session
      - name: session_length_seconds
        description: How long the session lasted in seconds
      - name: first_event
        description: First event within the session
      - name: last_event
        description: Last event within the session
      - name: first_page_visited
        description: The first page visited in the session
      - name: is_bounce
        description: Single-page session
  - name: fct_funnel_daily
    description: >-
      Funnel daily
    columns:
      - name: calendar_date
        description: Observation date
        tests:
          - unique
          - not_null
      - name: total_sessions
        description: Total amount of sessions
        tests:
          - not_null
      - name: sessions_with_pv
        description: Amount of sessions with page view
      - name: sessions_with_add_to_cart
        description: Amount of sessions when a product was added to cart
      - name: sessions_with_checkout
        description: Amount of sessions with checkout event
      - name: sessions_with_pv_percentage
        description: Percentage of all sessions that had a page view 
      - name: sessions_with_add_to_cart_percentage
        description: Percentage of page view sessions that had a add to cart event
      - name: sessions_with_checkout_percentage
        description: Percentage of add to cart sessions that had a checkout event


